# Generated by Django 6.0.6 on 2026-06-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                verbose_name='Высота, см',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='installation_type',
            field=models.CharField(
                choices=[
                    ('wall_mounted', 'Подвесной'),
                    ('vanity', 'На тумбе'),
                    ('floor_standing', 'Напольный'),
                    ('built_in', 'Встраиваемый'),
                    ('countertop', 'Накладной'),
                    ('other', 'Другой'),
                ],
                max_length=20,
                verbose_name='Монтаж',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                verbose_name='Длина, см',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=150, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(
                choices=[
                    ('faucet', 'Кран'),
                    ('sink', 'Раковина'),
                    ('bathtub', 'Ванна'),
                    ('shower', 'Душевая'),
                    ('pipe', 'Труба'),
                    ('toilet', 'Унитаз'),
                    ('other', 'Другое'),
                ],
                max_length=20,
                verbose_name='Вид',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(max_length=100, verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                verbose_name='Ширина, см',
            ),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(
                condition=models.Q(('length_cm__gt', 0)),
                name='product_length_gt_0',
            ),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(
                condition=models.Q(('width_cm__gt', 0)),
                name='product_width_gt_0',
            ),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(
                condition=models.Q(('height_cm__gt', 0)),
                name='product_height_gt_0',
            ),
        ),
    ]
