# Generated by Django 6.0.6 on 2026-06-27 16:37

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_fixed_categories_product_image_and_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.product_gallery_image_upload_path, verbose_name='Р¤РѕС‚РѕРіСЂР°С„РёСЏ')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='РћРїРёСЃР°РЅРёРµ С„РѕС‚Рѕ')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='РџРѕСЂСЏРґРѕРє')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product', verbose_name='РўРѕРІР°СЂ')),
            ],
            options={
                'verbose_name': 'Р¤РѕС‚РѕРіСЂР°С„РёСЏ С‚РѕРІР°СЂР°',
                'verbose_name_plural': 'Р¤РѕС‚РѕРіСЂР°С„РёРё С‚РѕРІР°СЂР°',
                'ordering': ('position', 'pk'),
            },
        ),
    ]
