# Generated by Django 6.0.6 on 2026-06-21 21:24

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=cart.models.default_delivery_date, verbose_name='Дата доставки'),
        ),
    ]
