# Generated by Django 6.0.6 on 2026-06-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hidden_from_history',
            field=models.BooleanField(default=False, verbose_name='Скрыт из истории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=12, verbose_name='Статус'),
        ),
    ]
