# Generated by Django 6.0.6 on 2026-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('awaiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('payment_failed', 'Ошибка оплаты'), ('shipped', 'Доставляется'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
