# Generated by Django 6.0.6 on 2026-06-27 17:59

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_apartment',
            field=models.CharField(blank=True, max_length=40, verbose_name='Кв./офис'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=cart.models.default_delivery_cost, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_entrance',
            field=models.CharField(blank=True, max_length=40, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_house',
            field=models.CharField(blank=True, max_length=40, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=180, verbose_name='Улица'),
        ),
    ]
